### ISSUE TITLE
Long term visualizations

### ISSUE THREAD

**Issue by omnibench** [nikic/llvm-compile-time-tracker#2] opened 2022-11-27 02:47 UTC
I'm very curious how the compile time perf of llvm has changed over the long term. However, if I enter a start date of, say, jan 1 of this year, the page just timeouts. Any way to see long term trends of llvm speed?

Thanks!

**Comment by nikic** [comment] 2022-12-04 09:13
The graph view always displays data for every single commit, which becomes untenable for longer date ranges. Maybe adding support for showing every Nth commit would work well enough for this purpose.

**Comment by nikic** [comment] 2022-12-04 10:26
Here is a long-term view since around the time I started collecting NewPM measurements for all configs: https://llvm-compile-time-tracker.com/graphs.php?stat=instructions%3Au&relative=on&startDate=2021-02-01&interval=100

To go earlier than that, need to also make the used configs configurable, so LegacyPM data is shown.

**Comment by nikic** [comment] 2022-12-04 11:34
Longer term data including legacy PM:
O3: https://llvm-compile-time-tracker.com/graphs.php?stat=instructions&startDate=2019-07-01&interval=100&configs=LegacyPM-O3%2CNewPM-O3
O0-g: https://llvm-compile-time-tracker.com/graphs.php?stat=instructions&startDate=2019-07-01&interval=100&configs=LegacyPM-O0-g%2CNewPM-O0-g

These use absolute numbers to keep the two graphs starting at separate times comparable.

**Comment by nikic** [comment] 2022-12-04 14:45
Closing this as done, let me know if anything is still missing here...

**Closed by nikic** 2022-12-04 14:45 UTC

**Comment by omnibench** [comment] 2022-12-04 21:09
Thank you very much, that's amazing!

Seems in general there is a mix of major wins and major regressions. I wonder what caused the massive spike in 7zip compiles. Anyways, seems like llvm is not... too much slower... in aggregate compared to 2 years ago

**Comment by nikic** [comment] 2022-12-04 21:59
The big 7zip regression is from the switch to C++ 17 by default. It increased the size of STL headers by a factor of 2.5x or so and the extra compile time is mostly just parsing those headers.
